### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by vineetbansal** [Paularossi/AdDownloader#3]
Hello - thanks for the great library!
I keep getting an `OAuthException` ("Application does not have permission for this action") on using the library and providing my access token (which I get from https://developers.facebook.com/tools/accesstoken - the "User Token"). Do you know if I'm supposed to get this token some other way?

I have granted all the permissions to my app, which I'm passing as the `project_name` argument here:
```
plt_ads_api = adlib_api.AdLibAPI(access_token, project_name = "<my_app_name>")
```

Comments on the web seem to indicate that this token is physically mailed to you after identity verification - just making sure this is correct?

Thanks!

**Comment by Paularossi** [comment]
Hi @vineetbansal,

It might be possible that the app you created doesn't have the right permissions for querying the Ad Library API. Have you followed the steps described [here](https://www.facebook.com/ads/library/api/?source=nav-header)? (see screenshot below)
<img width="479" alt="API steps" src="https://github.com/Paularossi/AdDownloader/assets/46716589/810e78af-c90f-4440-a1a6-ee285a5465ea">

When I created my developer profile and app, I didn't receive the access token via email; instead, I can either find it at the link you pasted above, or copy it from the [Graph API Explorer](https://developers.facebook.com/tools/explorer/). Additionally, you can always check if your access token is valid, by first querying the Ad Library API in the [Graph API Explorer](https://developers.facebook.com/tools/explorer/).

Here is an example of a query that you can paste into the Graph API Explorer:
`ads_archive?fields=id,page_name,ad_delivery_start_time&ad_reached_countries=BE&search_terms=pizza&active_status=ACTIVE&ad_type=all&ad_delivery_date_min=2024-07-09`
The output should look like this:
<img width="942" alt="graph api example" src="https://github.com/Paularossi/AdDownloader/assets/46716589/f4336f71-53f4-4273-bf4f-547743a28cfb">

If you get another `OAuthException` it means your access token does not have the permission to query the Ad Library API. You can try to [debug](https://developers.facebook.com/docs/facebook-login/guides/%20access-tokens/debugging) the access token, or create a new app with the right permissions.

I hope this helps! Feel free to reach out to me via email if you need further help!

By the way, the `project_name` doesn't need to contain the actual name of your app, it can be any name you like that describes the data you want to download.

**Comment by vineetbansal** [comment]
Thanks for the excellent help @Paularossi ! - my "individual verification" hadn't been going through for several days (it kept rejecting my Driving License, supposedly through some automated mechanism), and I realized that it was because I had entered an incorrect Date of Birth when creating my account. That, and I hadn't enabled 2-factor authentication.

Now that it has gone through, it looks like the next step is the confirmation step to "run ads about social issues, elections or politics.." (even though I don't plan to _run_ ads, only access their metadata through a library like yours) - **a code that will be snail mailed to me at my physical US address!** Once I confirm that, then I should be able to proceed with authenticating my app and getting past the `OAuthException`.

Thanks again for the detailed writeup - all this wasn't intuitive at all at first because there are so many similar-sounding options for account management.

**Comment by Paularossi** [comment]
@vineetbansal No problem! 
I agree that the process is somewhat not really straight-forward on Meta's side... and that this "running" ads part might sound a bit confusing, although it is indeed what you ultimately need...

I hope you receive your access token soon - I will close this issue for now (also since it's a problem on Meta's end, not related to this package).
Please feel free to reach out again should you need any help accessing the API!
