### ISSUE TITLE
Quiet NLTK downloads

### ISSUE THREAD

**Issue by LuckyLuuk12** [Paularossi/AdDownloader#5]
Hi, I really like this repo but I was wondering whether I can somehow quiet the nltk downloads.
I have not found something I could do about it in my code so I thought making this issue/suggestion would be better.
I have no experience with nltk or whatsoever but it looks like the [analysis.py](https://github.com/Paularossi/AdDownloader/blob/main/AdDownloader/analysis.py)
could have this:
```python
nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('vader_lexicon', quiet=True)
nltk.download('wordnet', quiet=True)
```
from lines 32 and onwards?

**Comment by Paularossi** [comment]
Hi @LuckyLuuk12,
Thanks for raising this point. I have implemented the changes and released a new version: [0.2.11](https://github.com/Paularossi/AdDownloader/releases/tag/v0.2.11)
